version: '2.0'
services:
  db:
    image: postgres
    environment:
     - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    network_mode: bridge

  web:
    #build: .
    image: dacrystal/tripal
    environment:
      - UPLOAD_LIMIT=${UPLOAD_LIMIT}
      - MEMORY_LIMIT=${MEMORY_LIMIT}
    links:
      - db:postgres
    ports:
      - ${WEB_PORT}:80
    volumes:
      - sites:/var/www/html/sites
      - private:/var/www/private
    network_mode: bridge

volumes:
  pgdata:
  sites:
  private:

